server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3308/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
wechat:
  code2session:
    url: https://api.weixin.qq.com/sns/jscode2session
    appid: wx36c5bf0e9e3779a5
    secret: 8503ad3520961721782a45967537ea85
    grant_type: authorization_code

mybatis:
  mapper-locations: classpath:com/spencer/springboot/dao/xml/*.xml
  type-aliases-package: com.spencer.springboot.po
  config-location: classpath:mybatis-config.xml